{
 "title": "APC UPS Monitoring",
 "description": "Dashboard for single APC UPS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "KWH_Cost", "query": "0.7915311" },
   {
    "name": "upsname",
    "label": "upsname",
    "query": "label_values(apc_status_numeric, upsname)"
   }
  ]
 },
 "panels": [
  { "title": "UPS - $upsname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "upsname" },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcups_battery_charge_percent{upsname=\"$upsname\"}",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "UPS Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apc_status_numeric{upsname=\"$upsname\"}",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Load Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(apcups_nominal_power_watts{upsname=\"$upsname\"}*(apcups_load_percent{upsname=\"$upsname\"}/100)) / apcups_nominal_power_watts{upsname=\"$upsname\"}",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apc_status_numeric{upsname=\"$upsname\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcups_time_left_seconds{upsname=\"$upsname\"} / 60"
    }
   ]
  },
  {
   "title": "Charge Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apcups_battery_charge_percent{upsname=\"$upsname\"}",
     "legendFormat": "Battery"
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcups_nominal_power_watts{upsname=\"$upsname\"}*(apcups_load_percent{upsname=\"$upsname\"}/100)"
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcups_nominal_power_watts{upsname=\"$upsname\"}*(avg_over_time(apcups_load_percent{upsname=\"$upsname\"}[$__interval])/100)"
    }
   ]
  },
  {
   "title": "Battery Transfers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcups_numtransfers{upsname=\"$upsname\"}"
    }
   ]
  },
  {
   "title": "Last Transfer To Battery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "apcups_numtransfers{upsname=\"$upsname\"}",
     "legendFormat": "{{ timetransfertobattery }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "apcups_load_percent{upsname=\"$upsname\"}",
     "legendFormat": "Percent"
    },
    {
     "expr": "apcups_nominal_power_watts{upsname=\"$upsname\"}*(apcups_load_percent{upsname=\"$upsname\"}/100)",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Transfer Reason",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "apcups_numtransfers{upsname=\"$upsname\"}",
     "legendFormat": "{{lasttransfer}}"
    }
   ]
  },
  {
   "title": "Last Transfer From Battery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "apcups_numtransfers{upsname=\"$upsname\"}",
     "legendFormat": "{{timetransferfrombattery}}"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "apcups_line_volts{upsname=\"$upsname\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "apcups_nom_input_volts{upsname=\"$upsname\"}",
     "legendFormat": "Nominal"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcups_line_volts{upsname=\"$upsname\"}"
    }
   ]
  },
  {
   "title": "Average UPS Load (Last 24hs)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apcups_nominal_power_watts{upsname=\"$upsname\"}*(avg_over_time(apcups_load_percent{upsname=\"$upsname\"}[24h])/100)"
    }
   ]
  },
  {
   "title": "Nominal Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcups_nom_input_volts{upsname=\"$upsname\"}"
    }
   ]
  },
  {
   "title": "Estimated  Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((apcups_nominal_power_watts{upsname=\"$upsname\"}*(avg_over_time(apcups_load_percent{upsname=\"$upsname\"}[24h])/100) * 24 * 30)/1000) * $KWH_Cost"
    }
   ]
  }
 ]
}