# Application container
FROM scratch
ARG TARGETARCH
ARG TARGETOS

ENV TARGETOS ${TARGETOS}
ENV TARGETARCH ${TARGETARCH}

ADD /apcupsd-exporter-$TARGETOS-$TARGETARCH /ups-exporter

EXPOSE ${LISTENADDR}

ENTRYPOINT ["/ups-exporter"]
